[build]
  publish = "public"
  command = "npm run build"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["serverless-http", "express", "cors", "body-parser", "dotenv", "googleapis", "google-auth-library"]
  included_files = ["routes/**", "services/**", "middleware/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200